name: Kernel CI (jflte)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v4

    - name: Getting Toolchain
      run: |
        sudo apt-get install lib32z1 ccache
        sudo git clone --depth 1 --branch android-12.0.0_r0.41 --single-branch https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 /opt/toolchains/arm-linux-androideabi-4.9/
    - name: Building Kernel
      run: |
        export KBUILD_BUILD_USER=notnoelchannel
        export KBUILD_BUILD_HOST=unlegacy-devices
        export CROSS_COMPILE=/opt/toolchains/arm-linux-androideabi-4.9/bin/arm-linux-androideabi-
        make -j$(nproc --all) ARCH=arm VARIANT_DEFCONFIG=jf_eur_defconfig lineageos_jf_defconfig
        make -j$(nproc --all)
    - name: Moving Output # CI only
      run: |
        mkdir -p /home/runner/work/output
        cp arch/arm/boot/zImage /home/runner/work/output/zImage
    - name: Uploading Output
      uses: actions/upload-artifact@v4
      with:
        name: zImage
        path: /home/runner/work/output/zImage
